name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '20.13.1'

    - name: Install dependencies
      run: pnpm i

    - name: Build and deploy
      run: |
        pnpm build:dev-vue3  # This should build your project
        cd dist
        tar czf dist.tar.gz *  # This assumes that your built files are in the 'dist' directory
        echo "Distribution package created: dist.tar.gz"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: jakejarvis/github-pages-deploy-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repository: ${{ github.repository }}
        branch: main
        folder: ./dist
        tarball: dist.tar.gz
