name: Deploy Pages

on:
  push:
    branches:
      - main # 这里只配置了main分支，所以只有推送main分支才会触发以下任务

jobs:
  pages:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.13.1
        uses: actions/setup-node@v2
        with:
          node-version: "20.13.1"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build:dev-vue3
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

